### ISSUE TITLE
403-Forbidden Error. 

### ISSUE THREAD

**Issue by SnehaJainM** [friedcheesee/IEEEsmartmentor#3]
I encountered an issue while using the chatbot feature in the InnerVerse application and while submitting the user details. When attempting to chat with the chatbot, I received the following error message:

![Screenshot (4)](https://github.com/friedcheesee/InnerVerse/assets/139670235/4b10acef-43fd-4fc0-846f-af561808b9f6)
![Screenshot (5)](https://github.com/friedcheesee/InnerVerse/assets/139670235/90a051b7-5c1e-438a-a6a3-206e0d1d44f4)

Submitting details...
Details are valid...
Error: The server is refusing to allow the request to proceed.
Response received from server: None
2024-03-06 11:42:22.611 Uncaught app exception
Traceback (most recent call last):
  File "c:\users\1234\documents\innerverse-main\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\1234\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\1234\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\1234\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I have checked the server endpoints and ensured they are correct.
The error occurs consistently whenever I attempt to submit details or chat with the chatbot.
I have reviewed the code but couldn't identify the source of the issue.
Any assistance in resolving this issue would be greatly appreciated.

**Comment by friedcheesee** [comment]
Hey, apologies for the delay, as the repo wasnt maintained. Also, would need more info to decode these kinds of errors, can't really tell whats the issue from this. Plus, the libraries have a changed a lot now, so the present version doesn't work.
